//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeryBigPipirka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Cheque = new HashSet<Cheque>();
        }
    
        public int ID_Order { get; set; }
        public int User_ID { get; set; }
        public string DateOrder { get; set; }
        public int Address_ID { get; set; }
        public int OrderStatus_ID { get; set; }
        public int Product_ID { get; set; }
        public int ProductsOnOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cheque> Cheque { get; set; }
        public virtual ShippingAddress ShippingAddress { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
    }
}
