//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeryBigPipirka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Cheque = new HashSet<Cheque>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int ID_Product { get; set; }
        public int Category_ID { get; set; }
        public string ProductName { get; set; }
        public string DescriptionProducts { get; set; }
        public int QuantityInStock { get; set; }
        public Nullable<int> ProductImage_ID { get; set; }
        public int PriceHistory_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cheque> Cheque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual PriceHistory PriceHistory { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductImage ProductImage { get; set; }
    }
}
